#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Yusei Shiozawa
#SPDX-License-Identifier: BSD-3-Clause
import sys


def tonum(s):
    try:
        return int(s)
    except:
        return float(s) 

total = 0
count = 0

ans=0
for line in sys.stdin:
    line = line.rstrip()
    ans+=tonum(line)
    count+=1

if count > 0:
    ave = ans/count
    print(f"合計:{ans}, 平均:{ave}")

else :
    print("エラー")
##print(ans)
